# Generated by Django 4.0.4 on 2022-07-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_saved_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='base.post'),
        ),
    ]
