# Generated by Django 4.0.4 on 2022-07-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='similar_account_suggestions',
            field=models.BooleanField(default=False),
        ),
    ]
