# Generated by Django 4.0.4 on 2022-07-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_userprofile_similar_account_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='logo',
            field=models.ImageField(default='empty_photo.png', upload_to='media/logo'),
        ),
    ]
