# Generated by Django 4.0.4 on 2022-09-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
