# Generated by Django 4.0.4 on 2022-10-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_post_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtag',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
