# Generated by Django 4.0.4 on 2022-10-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_post_hashtag_alter_hashtag_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='post',
        ),
    ]
