# Generated by Django 4.1.3 on 2023-01-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_alter_hashtag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_dimensions',
            field=models.CharField(choices=[('1', '1:1'), ('2', '4:5'), ('3', '16:9')], default='2', max_length=5),
        ),
    ]
