# Generated by Django 4.0.4 on 2022-06-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_poststape_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststape',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
