# Generated by Django 4.0.4 on 2022-06-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_poststape_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststape',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
    ]
