# Generated by Django 4.0.4 on 2022-06-16 17:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_alter_poststape_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostsTape',
            new_name='Post',
        ),
    ]
