# Generated by Django 4.0.4 on 2022-06-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_poststape_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user',
        ),
    ]
