# Generated by Django 4.0.4 on 2022-07-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_comment_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
