# Generated by Django 4.0.4 on 2022-07-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_userprofile_django_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='logo',
        ),
    ]
