# Generated by Django 4.0.4 on 2022-07-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_saved_post_alter_saved_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to='base.post'),
        ),
    ]
