# Generated by Django 4.0.4 on 2022-07-20 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_saved_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.post'),
        ),
    ]
