# Generated by Django 4.0.4 on 2022-07-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_post_likes_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='base.post'),
        ),
    ]
