# Generated by Django 4.0.4 on 2022-07-26 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0034_alter_userprofile_django_user_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='django_user_model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
