# Generated by Django 4.0.4 on 2022-07-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_userprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='logo',
            field=models.ImageField(default='media/logo/empty_photo.png', upload_to='media/logo'),
        ),
    ]
