# Generated by Django 4.0.4 on 2022-09-16 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_follower_follower_alter_follower_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
