# Generated by Django 4.0.4 on 2022-09-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_follower_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='created',
        ),
    ]
