# Generated by Django 4.0.4 on 2022-09-16 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_remove_follower_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
