# Generated by Django 4.0.4 on 2022-09-27 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0068_reply_related_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='related_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
