# Generated by Django 4.0.4 on 2022-09-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_alter_comment_options_alter_reply_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('', 'Prefer not to say')], max_length=17, null=True),
        ),
    ]
